about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('author/cat', views.AboutCatView.as_view(), name='cat'),
    path('author/i', views.AboutIView.as_view(), name='i')
]

api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from api.views import (FavoritesAPIView, IngredientsListAPIView,
                       PurchasesAPIView,
                       SubscriptionsAPIView)

router = DefaultRouter()

urlpatterns = [

    path("ingredients/", IngredientsListAPIView.as_view(),
         name="APIingredients"),
    path("favorites/", FavoritesAPIView.as_view(), name="APIfavorites"),
    path("unfavorites/<int:recipe_id>", FavoritesAPIView.as_view(),
         name="APIunfavorites"),
    path("subscriptions/", SubscriptionsAPIView.as_view(),
         name="APIsubscriptions"),
    path("unsubscriptions/<int:author_id>", SubscriptionsAPIView.as_view(),
         name="APIunsubscriptions"),
    path("purchases/", PurchasesAPIView.as_view(),
         name="APIpurchases"),
    path("unpurchases/<int:recipe_id>", PurchasesAPIView.as_view(),
         name="APIunpurchases"),

]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

urlpatterns = [
    path('auth/', include("users.urls")),
    path('api/v1/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('about/', include(('about.urls','about'), namespace='about')),
    path('', include("recipes.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

about/models.py
from django.db import models

# Create your models here.

about/views.py
from django.views.generic import TemplateView


class AboutAuthorView(TemplateView):
    template_name = "author.html"


class AboutTechView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        type_list = [['Для создания сайта:', 'Django v:3.1.2', 'DRF v:3.12.2 ',
                      'Python v:3.7.6', 'PostgreSQL v:12.5', 'Javascript',
                      'HTML 5',
                      'CSS 3'],
                     ['Для разворачивания на боевом сервере:', 'Docker',
                      'Nginx', 'Gunicorn'],
                     ['Для автаматического деплоя:', 'GitHub workflow']]
        context['type_list'] = type_list
        return context

    template_name = "tech.html"


class AboutCatView(TemplateView):
    template_name = "photocat.html"


class AboutIView(TemplateView):
    template_name = "photoi.html"

about/templates/author.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet"
          href="{% static 'recipes/pages/single.css' %}"/>{% endblock %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
    <body class="body">
    <main class="main container">
        <div class="main__header">
            <h1 class="single-card__title">Об авторе</h1>
        </div>
        <br>
        <div class="col-md-3 mb-3 mt-1">
            <div class="card">
                <div class="card-body"><h3 class="single-card__section-title">
                    Главное:</h3>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div style="margin-bottom:10px;">
                                <font size="4" face="Arial"><a
                                        href="{% static 'about/resume/Kalinkin_Sergey.pdf' %}">Резюме</a></font>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div style="margin-bottom:10px;">
                                <font size="4" face="Arial">
                                    <a href="https://github.com/Sergey-Aleksandrovich/foodgram-project">Этот
                                        проект на ГитХабе</a>
                                </font>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div style="margin-bottom:10px;">
                                <font size="4" face="Arial">
                                    <a href="{% url 'about:cat' %}">Та, без
                                        которой ничего бы не получилось</a>
                                </font>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div style="margin-bottom:10px;">
                                <font size="4" face="Arial">
                                    <a href="{% url 'about:i' %}">Мои
                                        фотокарточки</a>
                                </font>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="single-card__section">
            <h3 class="single-card__section-title">Кратко о моей
                жизни:</h3>
            <p class=" single-card__section-text">
                Привет, меня зовут Калинкин
                Сергей и я работал над данным проектом.
                Проект создавался для демонстрации моих навыков работодателю,
                надеюсь этой цели я смог добиться. Если конкретнее, то
                разрабатывал бэкенд часть, конечно много залазил в HTML код и
                немного в JS.
            </p>
            <p class=" single-card__section-text">
                Я родился и вырос в городе Новосибирске, всегда увлекали точные
                науки, поэтому учился на строителя, чем занимался около 6 лет
                попутно работая инженером технадзора и проектировщиком. Во
                время этого увлекательного пути любил автоматизировать свою
                учебу/работу, но инструментов в виде exel, mathcad и ещё
                нескольких специальных программ стало не хватать и захотелось
                расширить свои возможности, с помощью языка программирования
                Python. Так и начался мой путь к бэкенд разработке. С течением
                времени стал понимать, что IT сфера в целом мне ближе и было
                принято решение развиваться как разработчик.
            </p>
            <p class=" single-card__section-text">
                С радостью расскажу более подробно, чем занимался на работах,
                почему занимался написанием научных статей и как адаптироваться
                к катанию на сноуборде если вес изменился с 75 до 90 кг.</p>
        </div>
    </main>
    </body>
{% endblock %}

about/templates/photocat.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet"
          href="{% static 'recipes/pages/single.css' %}"/>{% endblock %}
{% block title %}Фото кошечки{% endblock %}
{% block content %}
    <body class="body">
    <main class="main container">
        <img src="{% static 'about/cat/1.jpg' %}" alt="Кошечка" vspace="30" hspace="30">
        <img src="{% static 'about/cat/2.jpg'  %}" alt="Кошечка" vspace="30" hspace="30">
        <img src="{% static 'about/cat/3.jpg'  %}" width="1075" alt="Кошечка" vspace="30" hspace="30">
    </main>
    </body>
{% endblock %}

about/templates/photoi.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet"
          href="{% static 'recipes/pages/single.css' %}"/>{% endblock %}
{% block title %}Фото кошечки{% endblock %}
{% block content %}
    <body class="body">
    <main class="main container">
        <img src="{% static 'about/i/1.jpg' %}" alt="Автор проекта" vspace="30" hspace="30">
        <img src="{% static 'about/i/2.jpg' %}" alt="Автор проекта" vspace="30" hspace="30">
        <img src="{% static 'about/i/3.jpg' %}" alt="Автор проекта" vspace="30" hspace="30">
        <img src="{% static 'about/i/4.jpg' %}" alt="Автор проекта" vspace="30" hspace="30">
        <img src="{% static 'about/i/5.jpg' %}" alt="Автор проекта" vspace="30" hspace="30">
        <img src="{% static 'about/i/6.jpg' %}" alt="Автор проекта" vspace="30" hspace="30">
    </main>
    </body>
{% endblock %}

about/templates/tech.html
{% extends "base.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet"
          href="{% static 'recipes/pages/single.css' %}"/>{% endblock %}
{% block title %}Технологии{% endblock %}
{% block content %}
    <body class="body">
    <main class="main container">
        <div class="main__header">
            <h1 class="single-card__title">Технологии</h1>
        </div>
            <p><font size="5" face="Arial"><b>
                В проекте использованы следующие технологии:
            </b></font></p>
            <ol>
                {% for type in type_list %}
                    <li>
                        <ul>
                            <p><font size="4" face="Arial"><b>{{ type.0 }}</b></font></p>
                            {% for tech in  type|slice:"1:" %}
                                <li style="margin-bottom:15px;" ,
                                    style="margin-top:10px;">
                                    <font size="4" face="Arial">
                                        {{ tech }}
                                    </font>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ol>
    </main>
    </body>
{% endblock %}