about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('author/cat', views.AboutCatView.as_view(), name='cat'),
    path('author/i', views.AboutIView.as_view(), name='i')
]

api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from api.views import (FavoritesAPIView, IngredientsListAPIView,
                       PurchasesAPIView,
                       SubscriptionsAPIView)

router = DefaultRouter()

urlpatterns = [

    path("ingredients/", IngredientsListAPIView.as_view(),
         name="APIingredients"),
    path("favorites/", FavoritesAPIView.as_view(), name="APIfavorites"),
    path("unfavorites/<int:recipe_id>", FavoritesAPIView.as_view(),
         name="APIunfavorites"),
    path("subscriptions/", SubscriptionsAPIView.as_view(),
         name="APIsubscriptions"),
    path("unsubscriptions/<int:author_id>", SubscriptionsAPIView.as_view(),
         name="APIunsubscriptions"),
    path("purchases/", PurchasesAPIView.as_view(),
         name="APIpurchases"),
    path("unpurchases/<int:recipe_id>", PurchasesAPIView.as_view(),
         name="APIunpurchases"),

]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

urlpatterns = [
    path('auth/', include("users.urls")),
    path('api/v1/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('about/', include(('about.urls','about'), namespace='about')),
    path('', include("recipes.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'recipes/favicon.ico' %}"/>
    <title>{% block title %}The Foodgram{% endblock %} | Foodgram</title>
    {% block style %}Добавить стиль{% endblock %}
</head>
<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}?breakfast=True&lunch=True&dinner=True" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/nav.html
<nav class="nav">
    <div class="nav__container container">
        {% if user.is_authenticated %}
            <ul class="nav__items list">
                <li class="{% if request.path == '/' %}nav__item nav__item_active{% else %}nav__item{% endif %}"><a href="{% url 'index' %}?breakfast=True&lunch=True&dinner=True" class="nav__link link">Рецепты</a></li>
                <li class="{% if request.path == '/subscriptions' %}nav__item nav__item_active{% else %}nav__item{% endif %}"><a href="{% url 'subscriptions' %}?breakfast=True&lunch=True&dinner=True" class="nav__link link">Мои подписки</a></li>
                <li class="{% if request.path == '/creation_recipe/' %}nav__item nav__item_active{% else %}nav__item{% endif %}"><a href="{% url 'creation_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                <li class="{% if request.path == '/favorites' %}nav__item nav__item_active{% else %}nav__item{% endif %}"><a href="{% url 'favorites' %}?breakfast=True&lunch=True&dinner=True" class="nav__link link">Избранное</a></li>
                <li class="nav__item"><a href="{% url 'purchases' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{{user.purchases.all.count}}</span></li>
            </ul>
            <ul class="nav__items list">
                <li class="{% if request.path == '/auth/password_change/' %}nav__item nav__item_active{% else %}nav__item{% endif %}"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                <li class="nav__item"><a href="{% url 'profile' user.username  %}?breakfast=True&lunch=True&dinner=True" class="nav__link link">{{ user.username }}</a></li>

            </ul>
        {% else %}
            <ul class="nav__items list">
                <li class="{% if request.path == '/' %}nav__item nav__item_active{% else %}nav__item{% endif %}"><a href="{% url 'index' %}?breakfast=True&lunch=True&dinner=True" class="nav__link link">Рецепты</a></li>
{#                <li class="nav__item nav__item_disabled"><a href="#" class="nav__link link">Список покупок <span class="badge badge_style_blue nav__badge" id="counter">4</span></a></li>#}
            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="{% url 'login' %}" class="{% if request.path == '/auth/login/' %}button button_style_blue{% else %}nav__link link{% endif %}">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="{% if request.path == '/auth/signup/' %}button button_style_blue{% else %}nav__link link{% endif %}">Создать аккаунт</a></li>
            </ul>
        {% endif %}
    </div>
</nav>