api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from api.views import (FavoritesAPIView, IngredientsListAPIView,
                       PurchasesAPIView,
                       SubscriptionsAPIView)

router = DefaultRouter()

urlpatterns = [

    path("ingredients/", IngredientsListAPIView.as_view(),
         name="APIingredients"),
    path("favorites/", FavoritesAPIView.as_view(), name="APIfavorites"),
    path("unfavorites/<int:recipe_id>", FavoritesAPIView.as_view(),
         name="APIunfavorites"),
    path("subscriptions/", SubscriptionsAPIView.as_view(),
         name="APIsubscriptions"),
    path("unsubscriptions/<int:author_id>", SubscriptionsAPIView.as_view(),
         name="APIunsubscriptions"),
    path("purchases/", PurchasesAPIView.as_view(),
         name="APIpurchases"),
    path("unpurchases/<int:recipe_id>", PurchasesAPIView.as_view(),
         name="APIunpurchases"),

]

foodgram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import handler404, handler500
handler404 = "recipes.views.page_not_found"  # noqa
handler500 = "recipes.views.server_error"  # noqa

urlpatterns = [
    path('auth/', include("users.urls")),
    path('api/v1/', include("api.urls")),
    path('admin/', admin.site.urls),
    path('about/', include(('about.urls','about'), namespace='about')),
    path('', include("recipes.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from .views import (RecipesFormView, RecipesFormViewSuccess, index_view,
                    profile_view, purchases_download_view, recipe_edit_view,
                    recipe_view, FollowsView, PurchasesView, FavoritesView,
                    recipe_delete_view, RecipesFormViewDeleteSuccess)

urlpatterns = [
    path("", index_view, name="index"),
    path("creation_recipe/", RecipesFormView.as_view(),
         name="creation_recipe"),
    path("creation_recipe_success/", RecipesFormViewSuccess.as_view(),
         name="creation_recipe_success"),
    path("profile/<str:username>", profile_view,
         name="profile"),
    path("recipe/<str:slug>", recipe_view,
         name="recipe"),
    path("purchases_download/", purchases_download_view,
         name="download"),
    path("<str:slug>/edit/", recipe_edit_view,
         name="recipe_edit"),
    path("<str:slug>/delete/", recipe_delete_view,
         name="recipe_delete"),
    path("delete_recipe_success/", RecipesFormViewDeleteSuccess.as_view(),
         name="delete_recipe_success"),
    path("subscriptions/", FollowsView.as_view(),
         name="subscriptions"),
    path("purchases/", PurchasesView.as_view(),
         name="purchases"),
    path("favorites/", FavoritesView.as_view(),
         name="favorites"),
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save

from recipes.utils import save_title_slug

User = get_user_model()


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, )

    def __str__(self):
        return self.name


class IngredientList(models.Model):
    title = models.CharField(max_length=100)
    dimension = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.title},{self.dimension}'


class Ingredients(models.Model):
    kind = models.ForeignKey(IngredientList, on_delete=models.CASCADE,
                             related_name='ingredients')
    quantity = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'{self.kind.title} {self.quantity}, {self.kind.dimension}'


class Recipes(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='recipes')
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='recipes/')
    description = models.TextField()
    ingredients = models.ManyToManyField(Ingredients)
    tags = models.ManyToManyField(Tag, related_name='recipes')
    time = models.PositiveSmallIntegerField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    publication_date = models.DateTimeField('date published',
                                            auto_now_add=True, db_index=True)

    def __str__(self):
        return self.title


class Follow(models.Model):
    following_date = models.DateTimeField('date follow',
                                          auto_now_add=True, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following')

    def __str__(self):
        return f'follower-{self.user}->following-{self.author}'


class Favorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='favorites')
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE,
                               related_name='favorites')

    def __str__(self):
        return f'user-{self.user}->recipe-{self.recipe}'


class Purchases(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='purchases')
    recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE,
                               related_name='purchases')

    def __str__(self):
        return f'user-{self.user}->recipe-{self.recipe}'


pre_save.connect(save_title_slug, sender=Recipes)

recipes/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, forms

from .models import IngredientList, Recipes


class IngredientsField(forms.Field):
    def clean(self, value):
        if isinstance(value, list):
            return value
        raise ValidationError(f'Необходимо ввести ингредиенты')


class RecipesForm(ModelForm):
    ingredients = IngredientsField(label='Ингредиенты')

    class Meta:
        model = Recipes
        fields = (
            'title', 'tags', 'ingredients', 'time', 'description', 'image')
        labels = {'title': 'Название рецепта',
                  'tags': 'Теги',
                  'time': 'Время приготовления',
                  'description': 'Описание',
                  'image': 'Загрузить фото'
                  }

    def clean_ingredients(self):
        set_ingredients = set()
        ingredients_form = self.cleaned_data['ingredients']
        ingredients_db = list(IngredientList.objects.values('title'))
        for ingredient_form in ingredients_form:
            set_ingredients.add(ingredient_form[0])
            for ingredient_db in ingredients_db:
                if int(ingredient_form[1]) <= 0:
                    raise ValidationError(
                        "Количество ингредиента должно быть больше 0")
                if ingredient_db['title'] == ingredient_form[0]:
                    break
                if ingredients_db[-1] == ingredient_db:
                    raise ValidationError(
                        "Выберите ингредиент из выпадающего списка")
        if len(set_ingredients) is not len(ingredients_form):
            raise ValidationError(
                "Выбирайте ингредиет только один раз")
        return ingredients_form

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView, View
from fpdf import FPDF

from foodgram.settings import PAGINATOR_PER_PAGE
from .forms import RecipesForm
from .models import (
    Favorites, Follow, IngredientList, Ingredients, Purchases, Recipes, User)


class PDF(FPDF):
    def header(self):
        self.image('logo.jpg', 10, 8, 33)
        self.add_font('DejaVu', '', 'DejaVuSansCondensed.ttf', uni=True)
        self.set_font('DejaVu', '', 15)
        self.cell(80)
        self.cell(30, 10, 'Список ингредиентов', 0, 0, 'C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.add_font('DejaVu', '', 'DejaVuSansCondensed.ttf', uni=True)
        self.set_font('DejaVu', style='', size=8, )
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')


def create_dict_ingredients(request):
    result = dict()
    purchases = Purchases.objects.filter(
        user=request.user).select_related('recipe').order_by(
        '-pk')
    for purchase in purchases:
        for ingredient in purchase.recipe.ingredients.all():
            if result.get(ingredient.kind.title):
                result[ingredient.kind.title] = [
                    result[ingredient.kind.title][0] + ingredient.quantity,
                    ingredient.kind.dimension]
            else:
                result[ingredient.kind.title] = [ingredient.quantity,
                                                 ingredient.kind.dimension]
    return result


def request_add_ingredients(data):
    data._mutable = True
    data['ingredients'] = []
    for key in data.keys():
        if key[:15] == 'nameIngredient_':
            index_number = key[15:]
            data['ingredients'].append(
                [data['nameIngredient_' + index_number],
                 data['valueIngredient_' + index_number],
                 data['unitsIngredient_' + index_number]])
    return data


def check_tegs(request):
    result = []
    if request.GET.get('breakfast') == 'True':
        result.append(1)
    if request.GET.get('lunch') == 'True':
        result.append(2)
    if request.GET.get('dinner') == 'True':
        result.append(3)
    return result


def index_view(request):
    tags = check_tegs(request)
    if not (request.GET.get('breakfast') or request.GET.get(
            'lunch') or request.GET.get('dinner')):
        return redirect(f'/?breakfast=True&lunch=True&dinner=True')
    recipe_list = Recipes.objects.filter(tags__in=tags).select_related(
        'author').order_by(
        '-publication_date').all().distinct()
    if request.user.is_authenticated:
        favorites_recipes = Recipes.objects.filter(
            favorites__user=request.user)
        purchases_recipes = Recipes.objects.filter(
            purchases__user=request.user)
    else:
        purchases_recipes = tuple()
        favorites_recipes = tuple()
    paginator = Paginator(recipe_list, PAGINATOR_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html',
                  {'page': page, 'paginator': paginator,
                   'favorites_recipes': favorites_recipes,
                   'purchases_recipes': purchases_recipes})


def profile_view(request, username):
    tags = check_tegs(request)
    author = get_object_or_404(User, username=username)
    recipe_list = Recipes.objects.filter(tags__in=tags,
                                         author=author).select_related(
        'author').order_by(
        '-publication_date').all().distinct()
    if request.user.is_authenticated:
        favorites_recipes = Recipes.objects.filter(
            favorites__user=request.user)
        following = Follow.objects.filter(user=request.user,
                                          author=author).exists()
    else:
        favorites_recipes = tuple()
        following = False
    paginator = Paginator(recipe_list, PAGINATOR_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'profile.html',
                  {'page': page, 'paginator': paginator,
                   'favorites_recipes': favorites_recipes,
                   'author': author, 'following': following})


def recipe_view(request, slug):
    recipe = get_object_or_404(Recipes, slug=slug)
    if request.user.is_authenticated:
        favorites = Favorites.objects.filter(user=request.user,
                                             recipe=recipe)
        following = Follow.objects.filter(user=request.user,
                                          author=recipe.author)
        purchase = Purchases.objects.filter(user=request.user, recipe=recipe)

    else:
        favorites = False
        following = False
        purchase = False

    return render(request, 'single_page.html',
                  {'favorite': favorites, 'recipe': recipe,
                   'following': following, 'purchase': purchase})


@login_required
def purchases_download_view(request):
    dict_ingredients = create_dict_ingredients(request)
    filename = request.user
    pdf = PDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_font('DejaVu', '', 'DejaVuSansCondensed.ttf', uni=True)
    pdf.set_font('DejaVu', '', 12)
    for ingredient in dict_ingredients:
        pdf.cell(0, 10,
                 f'{ingredient} {dict_ingredients[ingredient][0]},'
                 f' {dict_ingredients[ingredient][1]}', 1, 1)
    response = HttpResponse(
        pdf.output(f'shopping_list_{filename}.pdf', 'S').encode('latin-1'),
        'application/pdf')
    response['Content-Disposition'] = \
        f'attachment; ' \
        f'filename="shopping_list_{filename}.pdf"'
    return response


@login_required
def recipe_edit_view(request, slug):
    author = get_object_or_404(User, username=request.user)
    recipe = get_object_or_404(Recipes, slug=slug, author=author)
    form = RecipesForm(request.POST or None, files=request.FILES or None,
                       instance=recipe)
    if request.method == 'POST':
        form = RecipesForm(request_add_ingredients(request.POST) or None,
                           files=request.FILES or None, instance=recipe)

        if form.is_valid():
            recipe_form = form.save(commit=False)
            recipe.ingredients.clear()
            recipe.tags.clear()
            for ingredient in form.cleaned_data['ingredients']:
                ingredient_model = Ingredients.objects.filter(
                    kind=IngredientList.objects.get(title=ingredient[0]),
                    quantity=ingredient[1])
                if ingredient_model.exists():
                    recipe_form.ingredients.add(ingredient_model[0].pk)
                else:
                    ingredient_model = Ingredients.objects.create(
                        kind=IngredientList.objects.get(title=ingredient[0]),
                        quantity=ingredient[1])
                    recipe_form.ingredients.add(ingredient_model.pk)
            tags = form.cleaned_data['tags']
            recipe_form.tags.add(*tags)
            recipe_form.save()
            return redirect(f'/recipe/{slug}')
    return render(request, 'form_recipe.html',
                  {'form': form, 'recipe': recipe})


@login_required
def recipe_delete_view(request, slug):
    author = get_object_or_404(User, username=request.user)
    recipe = get_object_or_404(Recipes, slug=slug, author=author)
    recipe.delete()
    return redirect('delete_recipe_success')


@method_decorator(login_required, name='dispatch')
class FavoritesView(View):
    template_name = 'favorites.html'

    def get(self, request, *args, **kwargs):
        tags = check_tegs(request)
        recipe_list = Recipes.objects.filter(tags__in=tags,
                                             favorites__user=request.user) \
            .select_related('author') \
            .order_by('-publication_date') \
            .all().distinct()
        if request.user.is_authenticated:
            favorites_recipes = Recipes.objects.filter(
                favorites__user=request.user)
            purchases_recipes = Recipes.objects.filter(
                purchases__user=request.user)
        else:
            favorites_recipes = tuple()
            purchases_recipes = tuple()
        paginator = Paginator(recipe_list, PAGINATOR_PER_PAGE)
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)
        return render(request, self.template_name,
                      {'page': page, 'paginator': paginator,
                       'favorites_recipes': favorites_recipes,
                       'purchases_recipes': purchases_recipes})


@method_decorator(login_required, name='dispatch')
class PurchasesView(View):
    template_name = 'shop_list.html'

    def get(self, request, *args, **kwargs):
        purchases = Purchases.objects.filter(user=request.user).select_related(
            'recipe').order_by('-pk')
        return render(request, self.template_name,
                      {'purchases': purchases, })


class FollowsView(View):
    template_name = 'my_follow.html'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        follows = Follow.objects.select_related('author').filter(
            user=request.user).order_by('-following_date')
        author = []
        for follow in follows:
            author.append(follow.author)
        paginator = Paginator(follows, PAGINATOR_PER_PAGE)
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)
        return render(request, self.template_name,
                      {'page': page, 'paginator': paginator, })

recipes/templates/Favorites.html
{% extends "base.html" %}
{% block title %} Рецепты в избранном {% endblock %}
{% load static %}
{% load user_filters %}
{% block style %}<link rel="stylesheet" href="{% static 'recipes/pages/index.css' %}"/>{% endblock %}
{% block content %}
{% csrf_token %}
<body class="body">
    <main class="main container">
        <div class="main__header">
            {% if favorites_recipes.count == 0 %}
                <h1 class="main__title">Добавьте рецепт в избранное</h1>
            {% else %}
                <h1 class="main__title">Рецепты</h1>
                {% include 'tags_filter.html' %}
        </div>
                {% include 'recipe_item.html' %}
                {%  if page.paginator.num_pages > 1 %}
                    {%  include "pagination.html" %}
                {% endif %}
            {% endif %}
    </main>
  <script src="{% static 'recipes/js/components/MainCards.js' %}"></script>
  <script src="{% static 'recipes/js/components/Purchases.js' %}"></script>
  <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
  <script src="{% static 'recipes/js/config/config.js' %}"></script>
  <script src="{% static 'recipes/js/components/CardList.js' %}"></script>
  <script src="{% static 'recipes/js/components/Header.js' %}"></script>
  <script src="{% static 'recipes/js/api/Api.js' %}"></script>
  <script src="{% static 'recipes/js/index.js' %}"></script>
</body>
{% endblock %}

recipes/templates/MyFollow.html
{% extends "base.html" %}
{% block title %} Мои подписки {% endblock %}
{% load static %}
{% load user_filters %}
{% block style %}<link rel="stylesheet"href="{% static 'recipes/pages/myFollow.css' %}"/>{% endblock %}
{% block content %}
{% csrf_token %}
<body class="body">
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Мои подписки</h1>
        </div>
        <div class="card-list">
        {% include "user_item.html" with follows=page %}
        </div>
        {%  if page.paginator.num_pages > 1 %}
            {%  include "pagination.html" with page=page %}
        {% endif %}
    </main>
    <script src="{% static 'recipes/js/components/MainCards.js' %}"></script>
    <script src="{% static 'recipes/js/components/Header.js' %}"></script>
    <script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
    <script src="{% static 'recipes/js/components/MyFollow.js' %}"></script>
    <script src="{% static 'recipes/js/config/config.js' %}"></script>
    <script src="{% static 'recipes/js/api/Api.js' %}"></script>
    <script src="{% static 'recipes/js/myFollow.js' %}"></script>
</body>
{% endblock %}

recipes/templates/ShopList.html
{% extends "base.html" %}
{% block title %} Список покупок {% endblock %}
{% load static %}
{% load thumbnail %}
{% load user_filters %}
{% block style %}
    <link rel="stylesheet"
          href="{% static 'recipes/pages/shopList.css' %}"/>{% endblock %}
{% block content %}
    {% csrf_token %}
    <body class="body">
    <main class="main container">
        <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for purchase in purchases %}
                <li class="shopping-list__item" data-id="{{purchase.recipe.pk}}">
                    <div class="recipe recipe_reverse">
                        {% thumbnail purchase.recipe.image "480x480" crop="center" upscale=True as im %}
                            <a href="{% url 'recipe' purchase.recipe.slug %}" class="link" target="_blank"><img src="{{ im.url }}" alt="Картинка рецепта" class="recipe__image recipe__image_big"></a>
                        {% endthumbnail %}
                        <h3 class="recipe__title">{{purchase.recipe.title}}</h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{purchase.recipe.time}} мин.</p>
                    </div>
                    <a href="{% url 'recipe' purchase.recipe.slug %}" class="shopping-list__button link">Удалить</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'download' %}"><button class="button button_style_blue">Скачать список</button></a>
    </div>
    </main>
    <script src="{% static 'recipes/js/components/Header.js' %}"></script>
    <script src="{% static 'recipes/js/components/ShopList.js' %}"></script>
    <script src="{% static 'recipes/js/config/config.js' %}"></script>
    <script src="{% static 'recipes/js/api/Api.js' %}"></script>
    <script src="{% static 'recipes/js/shopList.js' %}"></script>
    </body>
{% endblock %}

recipes/templates/creation_recipe_done.html
{% extends "base.html" %}
{% load static %}
{% block title %} Успешное создание рецепта {% endblock %}
{% block style %}<link rel="stylesheet" href="{% static 'recipes/pages/form.css' %}">{% endblock %}
{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Вы успешно создали рецепт, поздравляю!</h1>
        </div>
    <p class="form__info-text"><a href="{% url 'profile' user.username %}?breakfast=True&lunch=True&dinner=True">Вернуться на свою страничку</a></p>
    </main>
{% endblock %}

recipes/templates/delete_recipe_done.html
{% extends "base.html" %}
{% load static %}
{% block title %} Успешное удаление рецепта {% endblock %}
{% block style %}<link rel="stylesheet" href="{% static 'recipes/pages/form.css' %}">{% endblock %}
{% block content %}
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Вы успешно удалили рецепт, поздравляю!</h1>
        </div>
    <p class="form__info-text"><a href="{% url 'profile' user.username %}?breakfast=True&lunch=True&dinner=True">Вернуться на свою страничку</a></p>
    </main>
{% endblock %}

recipes/templates/favorites.html
{% extends "base.html" %}
{% block title %} Рецепты в избранном {% endblock %}
{% load static %}
{% load user_filters %}
{% block style %}<link rel="stylesheet" href="{% static 'recipes/pages/index.css' %}"/>{% endblock %}
{% block content %}
{% csrf_token %}
<body class="body">
    <main class="main container">
        <div class="main__header">
            {% if favorites_recipes.count == 0 %}
                <h1 class="main__title">Добавьте рецепт в избранное</h1>
            {% else %}
                <h1 class="main__title">Рецепты</h1>
                {% include 'tags_filter.html' %}
        </div>
                {% include 'recipe_item.html' %}
                {%  if page.paginator.num_pages > 1 %}
                    {%  include "pagination.html" %}
                {% endif %}
            {% endif %}
    </main>
  <script src="{% static 'recipes/js/components/MainCards.js' %}"></script>
  <script src="{% static 'recipes/js/components/Purchases.js' %}"></script>
  <script src="{% static 'recipes/js/components/Favorites.js' %}"></script>
  <script src="{% static 'recipes/js/config/config.js' %}"></script>
  <script src="{% static 'recipes/js/components/CardList.js' %}"></script>
  <script src="{% static 'recipes/js/components/Header.js' %}"></script>
  <script src="{% static 'recipes/js/api/Api.js' %}"></script>
  <script src="{% static 'recipes/js/index.js' %}"></script>
</body>
{% endblock %}

recipes/templates/formRecipe.html
{% extends "base.html" %}
{% block title %} Рецепты {% endblock %}
{% load static %}
{% load user_filters %}
{% block style %}<link rel="stylesheet" href="{% static 'recipes/pages/form.css' %}"/>{% endblock %}
{% block content %}
<body class="body">
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">{% if recipe %}Редактирование рецепта{% else %}Создание рецепта{% endif %}</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="form__group" aria-required="{% if field.field.required %}true"{% else %}false"{% endif %}>
                <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
                <div class="form__field-group{% if field.label == 'Время приготовления' %} form__field-group_time{% endif %}">
                    {% if field.label == 'Название рецепта' %}
                        {{ field | addclass:"form__input" }}
                    {% elif field.label == 'Теги' %}
                        <div class="tags">
                            <div class="tags__item">
                                <input type="checkbox" name="tags" value="1" id="id_breakfast" class="tags__checkbox tags__checkbox_style_orange">
                                <label for="id_breakfast" class="tags__label">Завтрак</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="tags" value="2" id="id_lunch" class="tags__checkbox tags__checkbox_style_green">
                                <label for="id_lunch" class="tags__label">Обед</label>
                            </div>
                            <div class="tags__item">
                                <input type="checkbox" name="tags" value="3" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple">
                                <label for="id_dinner" class="tags__label">Ужин</label>
                            </div>
                        </div>
                    {% elif field.label == 'Ингредиенты' %}
                        <div class="form__field-group">
                            <div class="form__field-group-ingredientes">
                                <div class="form__dropdown">
                                    <input type="text" id="nameIngredient" class="form__input">
                                    <div class="form__dropdown-items"></div>
                                </div>
                                <input type="number" id="cantidad" class="form__input" min="0">
                                <label for="cantidad" class="form__label" id="cantidadVal">Единица измерения</label>
                            </div>
                            <div class="form__field-group-ingredientes-container">
                                {% if recipe %}
                                    {% for ing in recipe.ingredients.all %}
                                        <div class="form__field-item-ingredient" id="ing_{{ing.pk}}">
                                            <span>{{ing.kind.title}} {{ing.quantity}} {{ing.kind.dimension}}</span>
                                            <span class="form__field-item-delete"></span>
                                            <input id="nameIngredient_{{ing.pk}}" name="nameIngredient_{{ing.pk}}" type="hidden" value="{{ing.kind.title}}">
                                            <input id="valueIngredient_{{ing.pk}}" name="valueIngredient_{{ing.pk}}" type="hidden" value="{{ing.quantity}}">
                                            <input id="unitsIngredient_{{ing.pk}}" name="unitsIngredient_{{ing.pk}}" type="hidden" value="{{ing.kind.dimension}}">
                                        </div>
                                    {% endfor %}
                                {% else %}{% endif %}
                            </div>
                            <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                        </div>
                    {% elif field.label == 'Время приготовления'%}
                        {{ field | addclass:"form__input" }}
                        <label for="id_time" class="form__label">минут</label>
                    {% elif field.label == 'Описание'%}
                        {{ field | addclassrow:"form__textarea,8"}}
                    {% elif field.label == 'Загрузить фото' %}
                        <label for="id_file" class="form__file-button">Выбрать файл</label>
                        {{ field | addclass:"form__file" }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                    <span class="form__error">{{ field.errors }}</span>
                </div>
                </div>
            {% endfor %}
        <div class="form__footer">
            <button class="button button_style_blue">{% if recipe %}Редактировать рецепт{% else %}Создать рецепт{% endif %}</button>
        </div>
        </form>
    </div>
</main>
<script src="{% static 'recipes/js/components/Header.js' %}"></script>
<script src="{% static 'recipes/js/config/config.js' %}"></script>
<script src="{% static 'recipes/js/api/Api.js' %}"></script>
<script src="{% static 'recipes/js/utils/debouncing.js' %}"></script>
<script src="{% static 'recipes/js/formRecipe.js' %}"></script>
</body>
{% endblock %}

recipes/templates/my_follow.html
{% extends "base.html" %}
{% block title %} Мои подписки {% endblock %}
{% load static %}
{% load user_filters %}
{% block style %}<link rel="stylesheet"href="{% static 'recipes/pages/myFollow.css' %}"/>{% endblock %}
{% block content %}
{% csrf_token %}
<body class="body">
    <main class="main container">
        <div class="main__header">
            <h1 class="main__title">Мои подписки</h1>
        </div>
        <div class="card-list">
        {% include "user_item.html" with follows=page %}
        </div>
        {%  if page.paginator.num_pages > 1 %}
            {%  include "pagination.html" with page=page %}
        {% endif %}
    </main>
    <script src="{% static 'recipes/js/components/MainCards.js' %}"></script>
    <script src="{% static 'recipes/js/components/Header.js' %}"></script>
    <script src="{% static 'recipes/js/components/Subscribe.js' %}"></script>
    <script src="{% static 'recipes/js/components/MyFollow.js' %}"></script>
    <script src="{% static 'recipes/js/config/config.js' %}"></script>
    <script src="{% static 'recipes/js/api/Api.js' %}"></script>
    <script src="{% static 'recipes/js/myFollow.js' %}"></script>
</body>
{% endblock %}